# Use official n8n image
FROM n8nio/n8n:latest

# Expose default n8n port
EXPOSE 5678

# Database settings
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=postgres.railway.internal
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=railway
ENV DB_POSTGRESDB_USER=postgres
ENV DB_POSTGRESDB_PASSWORD=SxUToZyaTcyIvGFJaXjMAUcJbkVGMOTu

# Set environment variables
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=StrongPassword123
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

# Start n8n
ENTRYPOINT ["n8n"]
